# Generated by Django 2.0 on 2018-12-05 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_cornerlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornerlist',
            name='tag_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='corner',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
