# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180706_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media/', width_field='width_field'),
        ),
    ]
