# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-10 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180810_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
