# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', max_length=10000, null=True, upload_to='media/', width_field='width_field'),
        ),
    ]

