# Generated by Django 2.0 on 2018-11-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180910_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_image',
            field=models.ImageField(blank=True, height_field='height_field', max_length=10000, null=True, upload_to='posts', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', max_length=10000, null=True, upload_to='posts', width_field='width_field'),
        ),
    ]
