# Generated by Django 2.0 on 2018-12-06 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20181206_1132'),
    ]

    operations = [
   
        migrations.AddField(
            model_name='messaging',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
   
    ]
