# Generated by Django 2.0 on 2019-02-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20190111_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corner',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='corner',
            name='user',
        ),
        migrations.DeleteModel(
            name='CornerList',
        ),
        migrations.RemoveField(
            model_name='messaging',
            name='sender',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=1500, unique=True),
        ),
        migrations.DeleteModel(
            name='Corner',
        ),
        migrations.DeleteModel(
            name='Messaging',
        ),
    ]
