sudo: required
services:
  - docker

before_install:
    - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in .docker_env.enc -out .docker_env -d
    - docker-compose build

script:
  # - rm -rf docker-compose.yml && rm -rf docker-compose-local.yml
  - 'curl -X POST https://content.dropboxapi.com/2/files/download --header "Authorization: Bearer $DRPB" --header "Dropbox-API-Arg: {"path": "/software-application/sol/fullchain.pem"}" > ./nginx/fullchain.pem'
  - 'curl -X POST https://content.dropboxapi.com/2/files/download --header "Authorization: Bearer $DRPB" --header "Dropbox-API-Arg: {"path": "/software-application/sol/privkey.pem"}" > ./nginx/privkey.pem'
  - docker-compose -f docker-compose-local.yml up -d
  - docker-compose down
  # - ls nginx/sites-enabled
 

after_success:
  - docker build -t texplode/springs-web  .
  - docker build -t texplode/springs-nginx  ./nginx
  - docker build -t texplode/docker_smtp ./docker-smtp

  # Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take images and push them to dockerhub

  - docker push texplode/springs-web
  - docker push texplode/springs-nginx
  - docker push texplode/docker_smtp

 



 
# deploy:
#   provider: script
#   script: echo "yes" ssh $EC2_INSTANCE 'bash ./deploy.sh'
#   on:
#     branch: springs

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: springsoflife
  env: Springsoflife-env 
  bucket_name: springs-bucket
  # bucket_path: spring_bucket
  on:
    branch: springs
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

