sudo: required
services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose up -d
  - docker-compose down

after_success:
  - docker build -t texplode/springs-web  .
  - docker build -t texplode/springs-nginx  ./nginx
  - docker build -t texplode/docker_smtp ./docker-smtp
  - docker build -t texplode/debug_springs  ./debug_server

  
  

  # Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take images and push them to dockerhub

  - docker push texplode/springs-web
  - docker push texplode/springs-nginx
  - docker push texplode/docker_smtp
  - docker push texplode/debug_springs

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: sol
  env: Sol-env 
  bucket_name: springs-bucket
  # bucket_path: spring_bucket
  on:
    branch: springs
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

