sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
  -in .env.enc -out .env -d
- cat .env >> .env
- ls denv
- docker-compose build
script:
- 'curl -X POST https://content.dropboxapi.com/2/files/download --header "Authorization:
  Bearer $DRPB" --header "Dropbox-API-Arg: {"path": "/software-application/sol/fullchain.pem"}"
  > ./nginx/fullchain.pem'
- 'curl -X POST https://content.dropboxapi.com/2/files/download --header "Authorization:
  Bearer $DRPB" --header "Dropbox-API-Arg: {"path": "/software-application/sol/privkey.pem"}"
  > ./nginx/privkey.pem'
- docker-compose -f docker-compose-local.yml up -d
- docker-compose down
after_success:
- docker build -t texplode/springs-web  .
- docker build -t texplode/springs-nginx  ./nginx
- docker build -t texplode/docker_smtp ./docker-smtp
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push texplode/springs-web
- docker push texplode/springs-nginx
- docker push texplode/docker_smtp
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: springsoflife
  env: Springsoflife-env
  bucket_name: springs-bucket
  on:
    branch: springs
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
