version: '3'

services:

  web:
    image: texplode/springs-web
    tty: true
    command: /bin/sh -c "gunicorn springs.wsgi:application --bind 0.0.0.0:8009 && python manage.py migrate"
    env_file: .docker_env

  nginx:
    image: texplode/springs-nginx
    volumes:
      - /etc/letsencrypt/live/missions.springsoflifeg.com-0001:/etc/letsencrypt/live/missions.springsoflifeg.com-0001
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always
 

  smtp:
    image: texplode/docker_smtp
    ports:
     - "587:587"


