version: '3'

services:

  # db:
  #   restart: always
  #   image: postgres:alpine
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: "trust"
  #   volumes:
  #     - spring_data:/var/lib/postgresql/data/
  #   networks:
  #     - springs_db_nw
  web:
    image: texplode/springs-web 
    tty: true
    command: /bin/sh -c "gunicorn springs.wsgi:application --bind 0.0.0.0:8009 && python3 manage.py migrate"
    # volumes:
    #   - .:/var/www/app/
    #   - staticfiles:/var/www/app/staticfiles
    # depends_on:
    #   - db
    # env_file: .env
    networks:
      - springs_nw
      # - smtp_net

  nginx:
    image: texplode/springs-nginx
    # build: ./nginx
    # volumes:
    #   - staticfiles:/staticfiles
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    networks:
      - springs_nw



  smtp:
    build:
      context: ./docker-smtp
    ports:
     - "587:587"
    # env_file: .env
    networks:
      - smtp_net
      - springs_nw

# volumes:
#   spring_data:
#   staticfiles:


networks:
  # springs_db_nw:
  #   driver: bridge
  springs_nw:
    driver: bridge
  smtp_net:
    driver: bridge