# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', help_text='Enter Your Name', max_length=50),
        ),
    ]
