# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20180802_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='name',
        ),
    ]
