# Generated by Django 2.0 on 2019-01-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
