# Generated by Django 2.2.5 on 2019-09-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0003_auto_20190201_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
