# Generated by Django 2.2.5 on 2019-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0004_auto_20190919_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='village',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='image',
            field=models.ImageField(upload_to='https://None.s3.amazonaws.com/media/'),
        ),
    ]
