# Generated by Django 2.0 on 2019-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0006_auto_20191005_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchplant',
            name='village',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='educationalmission',
            name='village',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='growmission',
            name='village',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicalmission',
            name='village',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='praywithus',
            name='village',
            field=models.CharField(default='', max_length=100),
        ),
    ]
