# Generated by Django 2.0 on 2019-10-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0009_partnerwithus_servewithus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='outreach')),
                ('prayer_point', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='praywithus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='praywithus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='praywithus',
            name='title',
        ),
        migrations.RemoveField(
            model_name='praywithus',
            name='village',
        ),
        migrations.AddField(
            model_name='praywithus',
            name='Date',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='prayerpoint',
            name='pray_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pray_time', to='sol.PrayWithUs'),
        ),
    ]
