# Generated by Django 3.0.8 on 2020-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0013_auto_20200807_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ministryBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='outreach')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
