# Generated by Django 2.2.9 on 2021-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0014_ministrybackground'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchplant',
            old_name='description',
            new_name='write_up',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='description',
            new_name='write_up',
        ),
        migrations.RenameField(
            model_name='educationalmission',
            old_name='description',
            new_name='write_up',
        ),
        migrations.RenameField(
            model_name='growmission',
            old_name='description',
            new_name='write_up',
        ),
        migrations.RenameField(
            model_name='medicalmission',
            old_name='description',
            new_name='write_up',
        ),
        migrations.RenameField(
            model_name='mtc',
            old_name='description',
            new_name='write_up',
        ),
        migrations.RenameField(
            model_name='outreach',
            old_name='title',
            new_name='village',
        ),
        migrations.RenameField(
            model_name='outreach',
            old_name='description',
            new_name='write_up',
        ),
        migrations.RenameField(
            model_name='partnerwithus',
            old_name='description',
            new_name='write_up',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='title',
            new_name='village',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='description',
            new_name='write_up',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='title',
            new_name='village',
        ),
        migrations.RemoveField(
            model_name='village',
            name='description',
        ),
        migrations.AddField(
            model_name='village',
            name='write_up',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(null=True, upload_to='outreach'),
        ),
    ]
