# Generated by Django 2.2.9 on 2021-08-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0015_auto_20210804_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChurchPlant',
            new_name='MissionFields',
        ),
    ]
